### ISSUE TITLE
Double-click a test result in Caraya GUI to open the test VI

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#1]
It would be great if double-clicking a test result in the GUI should open the test VI and highlight the assertion on the block diagram. This would make it easy to find and fix the failure -- right now, it's pretty difficult to actually find the point of failure in the unit test code.

![2015-11-25_12-14-52](https://cloud.githubusercontent.com/assets/381432/11408509/6ae4361e-936e-11e5-801c-7b223de0d111.png)

**Comment by tmaila** [comment]
This has been on the top of the list of next features to implement. I'm not sure if there are technical means of finding the actual node that failed but I believe we can definitely find the VI that failed and open the block diagram upon double clicking the entry.

**Comment by jimkring** [comment]
Yes, opening the VI that failed is a great step forward - solves 95% of the use case.




If the assertion VIs are reentrant then maybe we can get a clone reference and map that to the subVI reference on the block diagram (but maybe not).



—

**Comment by tmaila** [comment]
Opening the block diagram is now implemented in 0.3. Test VIs are re-entrant but not sure if there would be a way to map the VI clone reference to a block diagram node reference and then somehow highlight that.

**Comment by jimkring** [comment]
Thanks. This is a very nice enhancement!

**Comment by jimkring** [comment]
BTW, I found a very minor bug: https://github.com/JKISoftware/Caraya/issues/3
