### ISSUE TITLE
Run continuously test VI causes freezing of Caraya window, even when test VI is stopped.

### ISSUE THREAD

**Issue by kosist** [JKISoftware/Caraya#10]
It's not a bug, I guess, and maybe it's difficult something to do with it, but here is a description.
1. VI contains test (define test -> vi under the test -> assert condition).
2. Run VI, press "Run Continuously".
3. Caraya window is opened, updates test results.
4. When one tries to close Caraya window (and test vi is still running), Caraya window is not closed.
5. Stop test VI.
6. Caraya window is still giving out test results to the list.
7. After some time it is closed.

I used LabVIEW 2013, SP1, 32-bit; Windows 7 64-bit, Intel Core i3-2348M (2.3 GHz), 4 GB RAM.

I know, that intentionally noone will run the vi continuously, but if it happens by mistake (as in my case)...

**Comment by tmaila** [comment]
This is not a bug. The run continuously ends up queuing a huge number of tests to the test queue and it takes time to process them all.
