### ISSUE TITLE
Regression with user.lib and OpenG dependency

### ISSUE THREAD

**Issue by volks73** [JKISoftware/Caraya#103]
Please see #23 for background and context. Caraya v0.6 moved the OpenG dependencies to internal but Caraya v1.0 appears to have dropped the internal OpenG dependency and is using the `user.lib` OpenG dependency. This is causing the same complication with the "save for previous" feature and process described in #23. Note, this time I am using LabVIEW 2018 and Caraya v1.0.

The inclusion of the `user.lib` can be observed in the dependencies for the LabVIEW project of the [LIBSSH2-LabVIEW](https://github.com/fieldrndservices/libssh2-labview) project, for reference.

I might be missing something, so any information and/or direction would be greatly appreciated.

**Comment by francois-normandin** [comment]
OpenG libs included in package (namespaced) so no reference to OpenG VIs under user.lib.
This is included in release 1.1.0. Please re-open this case if you see any problem.
