### ISSUE TITLE
Documentation: Open Caraya CLI in context of LabVIEW Project

### ISSUE THREAD

**Issue by ThatsTheEnd** [JKISoftware/Caraya#105]
Hey Caraya Team,

first of all: immensly helpful tool that you put out there!
When we call our VIs from the CLI, we need them openend in the context of the project. The reason is the following: when we build hardware drivers, we build them with the "normal" HW-VI calls and with a conditional disable structure ["Hardware Enabled" == False] so that we can test the architecture without the hardware. When we now call the VI as instructed on your [CLI Wiki site](https://github.com/JKISoftware/Caraya/wiki/Command-Line-Interface) it opens in the pure LabVIEW context and the default case (i.e. hardware enabled) is executed. 
It would be extremly helpful to add to the documentation that you can open the VI in the context of the project by changing the syntax:

`"C:\Program Files (x86)\National Instruments\LabVIEW 2019\LabVIEW.exe" "C:\Projects\PathToMyProject\MyProj.lvproj" "C:\Program Files (x86)\National Instruments\LabVIEW 2019\vi.lib\addons\_JKI Toolkits\Caraya\Caraya CLI.vi" -- -s "C:\Projects\PathToMyUnitTests" -x "C:\Users\UserName\Desktop\All tests.xml" -v 0`

Thanks a lot otherwise for the tool and keep up with the outstanding work!
Cheers,
Niko

**Comment by francois-normandin** [comment]
Excellent suggestion @ThatsTheEnd 
This has been added to the wiki

https://github.com/JKISoftware/Caraya/wiki/Command-Line-Interface
