### ISSUE TITLE
Test names (in JUnit report) for 1.1.0 Pre-release are using the VI File Name instead of Test Name

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#109]
@francois-normandin I did a little testing.

I created a JUnit report file using [version 1.0.2.115](https://github.com/JKISoftware/Caraya/releases/tag/1.0.2) and then tested using [1.1.0 Pre-release](https://github.com/JKISoftware/Caraya/releases/tag/1.1.0) and I get slightly different results in the output JUnit report file, shown below.

1.1.0 Pre-release seems to be using the test VI's file name as the test name/label (what I observed), instead of the Label argument passed into Define Test (what I expected).

![image](https://user-images.githubusercontent.com/381432/100525380-3c727200-3175-11eb-955d-20a077db1c9b.png)

**Comment by francois-normandin** [comment]
Hi @jimkring ,
Thanks Jim for the report.
Indeed, this discrepancy was found while investigating issue #108 . The test name was replaced with the last element of the call chain, but it was a mistake. It will be fixed for the released version.

Thanks for the independent corroboration!

François

**Comment by jimkring** [comment]
Great! Glad it's on the radar and happy to be of some small help :)

**Comment by francois-normandin** [comment]
Fixed in build 118

**Comment by jimkring** [comment]
@francois-normandin  I just did a test of build 118. It's looking really good!

I did notice that in the JUnit XML results the **testsuite name** is now correctly using the test Label argument passed into Define Test, yet **testcase classname** is still using the VI's file name (instead of the test's Label).

![image](https://user-images.githubusercontent.com/381432/100696961-9d52a380-3349-11eb-83d3-eeaa828713b2.png)

**Comment by francois-normandin** [comment]
This was an intended change to address issue #104 .
@jimkring @ChrisStrykesAgain 
Suggestions? What should classname contain in the JUnit report? Should the call chain be reported differently?

**Comment by ChrisStrykesAgain** [comment]
I think part of the problem here is that as I understand it, there isn't an official schema so everyone (in the greater programming community) interprets it differently. The closest I can find is here: http://windyroad.com.au/dl/Open%20Source/JUnit.xsd

There are some notable deviations from that format in the Caraya output, but that doesn't seem to be an uncommon situation among frameworks that output xUnit results. Maybe the best option would be to have the "traditional" xUnit output that Caraya always has had, then have a "strict xUnit" output option that falls more in line with the schema I referenced above?

**Comment by ChrisStrykesAgain** [comment]
Maybe a better link: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

**Comment by francois-normandin** [comment]
One thing to remember too: this is the shipping Caraya JUnit format, but it is very simple to overwrite this test report and provide a different output, which would still be JUnit compatible.

**Comment by ChrisStrykesAgain** [comment]
@francois-normandin , I agree. Maybe it's best to leave the shipping code as it was, and then someone can write a different report generator that adheres to the schema a bit more rigidly if they desire. That someone might be me, but I won't commit to it right now.

**Comment by jimkring** [comment]
I agree this is challenging, because it seems that the JUnit model of **_TestSuite >> TestCase >> test_method_** doesn't really map into how everyone else does it.

I'm currently looking at hot GitLab shows test results.

Here's a fragment of the report.xml that I have Caraya (1.1.0.118) generate.

```
<testsuites>
<testsuite name="Test GetLanguages" errors="0" skipped="0" tests="3" failures="0" timestamp="2020-12-01T09:54:46">
<testcase classname="TestGetLanguages.vi" name="Empty dictionary path returns empty array of languages"/>
<testcase classname="TestGetLanguages.vi" name="Getting Languages after reading test dictionary doesn&apos;t return error"/>
<testcase classname="TestGetLanguages.vi" name="Getting Languages after reading Test Dictionary doesn&apos;t return empty array of languages"/>
</testsuite>
<testsuite name="Test Localize Phrase" errors="0" skipped="0" tests="4" failures="0" timestamp="2020-12-01T09:54:52">
<testcase classname="TestGetLocalizedPhrase.vi" name="Localized Phrase with valid key in different langauges does not return error"/>
<testcase classname="TestGetLocalizedPhrase.vi" name="Localize Phrase with valid key in different languages returns different text"/>
<testcase classname="TestGetLocalizedPhrase.vi" name="Getting localized phrase in nonexistent language returns empty string"/>
<testcase classname="TestGetLocalizedPhrase.vi" name="Getting localized phrase in nonexistant language returns error"/>
</testsuite>
```

GitLab has test "Suite" and "Name" fields:

![image](https://user-images.githubusercontent.com/381432/100779203-e0019380-33bc-11eb-95c6-f14b921675fc.png)

It appears that GitLab sort of ignores the JUnit `<testsuite></testsuite>` information and just uses the `<testcase></testcase>` elements' information.

GitLab seems to use the JUnit `classname` attribute (of `<testcase></testcase>`) as the test "Suite" and it uses the `name` attribute (of `<testcase></testcase>`) as the test "Name".

I agree that maybe users will want to customize the JUnit reporting, and maybe there would even be a specific GitLab test report output.

**Comment by francois-normandin** [comment]
Are we then in agreement that we revert the classname to its original input value for version 1.1.0, and continue the discussion in thread #111 ?

**Comment by jimkring** [comment]
I've re-read thread #111 and I don't totally understand the implications.

Yet, I think it is true that for the JUnit report the `classname` attribute should always be the Label passed into Define Test.vi and the `name` attribute should be the Label passed into Assert.vi

**Comment by francois-normandin** [comment]
I think what I meant was that we can use thread 111 to chat about an alternative JUnit report type, but agree to leave the "legacy Caraya JUnit format" (for lack of better term) as it was. This format is already used and relied upon in CI processes, so it is best not to burn bridges. 

The current JUnit type would remain the default shipping example, and anything else we come up with would either be provided as an add-on, or incorporated as another possible choice in the polymorphic selector, should we think it is valuable to distribute as a core Caraya report.

**Comment by jimkring** [comment]
@francois-normandin yes, I agree it's best not to change the default JUnit report format in 1.1 and to leave it as it was in 1.0. Thanks.

**Comment by francois-normandin** [comment]
Great @jimkring 
I've reverted the code and will have a build 119 soon for testing. I'll mark it as pre-release until you make sure it outputs the same report as 1.0.x.

**Comment by jimkring** [comment]
@francois-normandin sounds like a great plan -- I'll test it when it's ready. Thanks!

**Comment by francois-normandin** [comment]
released (build 119).

**Comment by neilpate** [comment]
Did this discussion ever get any further?

I am starting my CI journey in LabVIEW. Several of my colleagues have configured a GitHub + Jenkins + LabVIEW solution and we are looking at the Test Results that Jenkins displays and as @jimkring commented the hierarchy does not map perfectly.

I tried to create a new report type but LabVIEW will not let me inherit from Test Report.JUnit. I was going to do this so that I can override the Export.vi

**Comment by francois-normandin** [comment]
Hi @neilpate , 

discussion on this has been moved to #111.

I'm surprised you can't inherit from the TestReport.JUnit class. I just tested it and it worked fine. 
As an alternative, you could simply copy and rename that class instead. Most of the code in Export.vi is private and would become dead code anyway, so you'll end up with a more lightweight solution if you just create a sibling class.

**Comment by neilpate** [comment]
@francois-normandin I think my problem was I had the Caraya.lvlib open or had just run a test or something so the library was locked.
