### ISSUE TITLE
Add "is_close" assertion for floating point comparison

### ISSUE THREAD

**Issue by StefanD986** [JKISoftware/Caraya#11]
Due to how floating point numbers are represented in a computer, equality checking of floating point numbers is not trivial.

Since this is a commen use case, it would be nice to have a assertion VI that takes care of the details such that not every Caraya user has to craft their own solution. 

See following two links for a explanation and a possible solution:
http://floating-point-gui.de/errors/comparison/
http://www.ni.com/white-paper/7612/en/

**Comment by neilpate** [comment]
I would also like this.

Currently I am porting some reasonably complicated calculations from C# (DLL) code to LabVIEW, and I expect some of my results to be ever so slightly different. At the moment I am using the Equals assertion but I would feel more comfortable using an is_close or similar.

**Comment by francois-normandin** [comment]
I created a pull request for this feature. Please review and comment!

**Comment by francois-normandin** [comment]
I chose "Tolerance" instead of "Epsilon", to allow both absolute or relative comparison.
Defaults to epsilon = 1E-6 in this proposed change.

**Comment by neilpate** [comment]
There is a bug if the number being tested is negative and the tolerance option is used. The In Range test will fail as the upper and lower limit are now swapped in terms of their magnitude. 

![assert float](https://user-images.githubusercontent.com/7802334/36467926-c22f7ce8-16e9-11e8-8cb6-03145d22a77b.PNG)

**Comment by francois-normandin** [comment]
Confirmed. I'll add a test case for negative numbers.

This is the fix:
![image](https://user-images.githubusercontent.com/11728548/36480094-09c7652c-16d9-11e8-8574-0febe2eba8f1.png)

**Comment by francois-normandin** [comment]
I'm currently unable to push changes to the remote float_tolerance branch. I'll check in with JKI.

**Comment by francois-normandin** [comment]
merged to Master branch.
This will be available in the next release.

**Comment by jimkring** [comment]
@francois-normandin and I discussed and decided to rename as "Assert Almost Equal_Float" similar to numpy: https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.testing.assert_almost_equal.html)

**Comment by francois-normandin** [comment]
Implemented in release 0.6.0
