### ISSUE TITLE
Add test results (Pass/Fail) output on "Run Tests.vi"

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#112]
Often, I want to run tests programmatically (using Run Tests.vi) and I want to both (A) save a test report to disk and also (B) know programmatically if any tests failed (so that I can abort a build process).

However, I can't seem to do both, **in a single call** to "Run Tests.vi"

Would it make sense to add a test results output as a Boolean (called "All Passed?")?

And/or would it make sense to output the resulting Test Report object?

![image](https://user-images.githubusercontent.com/381432/100920699-56bb9100-3490-11eb-9509-6bd1c108f4dd.png)

**Comment by francois-normandin** [comment]
We added the test report class as an output to the test suite. It seems reasonable to entertain the same with a run tests, which creates a test suite in the background.

**Comment by francois-normandin** [comment]
This is now in the develop branch and fully functional. 
As mentioned previously, with the Test Result class exposed as an output terminal for Test Suites, it was effectively a matter of exposing it further to the Run Tests method, which involved only adding a terminal to each polymorphic instance.

This should make it easily to version 1.2.
It didn't cause any change that would have an effect on build checks staying all green lit.

![image](https://user-images.githubusercontent.com/11728548/102019937-1ee00380-3d44-11eb-9817-787b7bc2c056.png)

**Comment by francois-normandin** [comment]
![image](https://user-images.githubusercontent.com/11728548/102019974-59e23700-3d44-11eb-8efe-93ad6d844635.png)

**Comment by jimkring** [comment]
Fantastic!
-- 
Jim Sent from my mobile.

**Comment by felipefoz** [comment]
I am also looking forward to this feature. I did write a post on the forums, but only after that I saw this issue.

https://forums.jki.net/topic/3532-test-results-using-test-runner-folder-discovery

**Comment by francois-normandin** [comment]
Included in 1.2.0 to be released soon
https://github.com/JKISoftware/Caraya/milestone/6
