### ISSUE TITLE
Make Get Library Info.vi Public

### ISSUE THREAD

**Issue by felipefoz** [JKISoftware/Caraya#121]
Hey,

I would like to propose if possible, to convert this vi to a public scope to be accessed outside this library.
The usage will vary, but it will be mainly used to check the Caraya Version in automated processes.

![image](https://user-images.githubusercontent.com/63814202/103693852-b79b2500-4f78-11eb-9204-4c89d5fedb75.png)

Thanks.

**Comment by francois-normandin** [comment]
@felipefoz That's a good point. This particular node is being scripted during the build process, so I will leave it untouched and simply create a wrapper to expose the info.

**Comment by felipefoz** [comment]
Nice. That will do the job as well. Thanks.

**Comment by francois-normandin** [comment]
Included in 1.2.0 to be released soon
https://github.com/JKISoftware/Caraya/milestone/6
