### ISSUE TITLE
Make build to PPL possible

### ISSUE THREAD

**Issue by HenrikDueholm** [JKISoftware/Caraya#127]
A minor modification of 'Linker.Find Tests and Suites.vi' allows Caraya to be built to and used as a PPL ([Linker.Find Tests and Suites.zip](https://github.com/JKISoftware/Caraya/files/6052228/Linker.Find.Tests.and.Suites.zip), should be saved to 2013)

It was extremely simple to get Caraya up and running as a PPL. The only other change I made was moving 'New Test (Caraya).vi' out of the library as it was found as a test when called from a PPL.

Note that it's either/or. The PPL version cannot call regular asserts and vice versa. And the menus are still only for the regular installation...

I propose that you implement the modifications to make PPL building possible from the get go. The change is minor and should not impact performance.

Picture of modifications that allow Caraya to run from a PPL:
![image](https://user-images.githubusercontent.com/63071979/109350719-4f7e0680-7878-11eb-9e24-9d9c707e8a30.png)

![New Test (Caraya)](https://user-images.githubusercontent.com/63071979/109350858-881de000-7878-11eb-92c2-c987fd87e660.jpg)

Project I've used to build PPL can be found [here](https://github.com/HenrikDueholm/LV32.2020..ProjectBuilder/tree/main/Class/Caraya%20Unit%20Test/PPL%20Project). Built PPL [here](https://github.com/HenrikDueholm/LV32.2020..PPL.ProjectBuilder).

Thank you for all the work you've put into this!

**Comment by francois-normandin** [comment]
@HenrikDueholm thanks for the suggestions. Building Caraya directly into a PPL would be a welcome improvement for many developers out there, I'm sure. 

I have a question about the template `New Test (Caraya)` 's removal from the library. The VI is already supposed to be explicitely removed from the linker info. If we were to make sure it gets excluded in the PPL build as well, wouldn't it be better to have a PPL-version of the template, one which would call the PPL-built assert methods?

I don't have much experience with PPLs myself, so my follow-up question might be dumb: Are the PPL-built methods discoverable in QuickDrop? If so, do you think there is a way to differentiate between the PPL and non-PPL versions of a method?

**Comment by francois-normandin** [comment]
Pending a few automated updates to the Caraya package a pre-build step, this issue will be resolved and PPL will be buildable from Caraya source as of release 1.2.0.

![image](https://user-images.githubusercontent.com/11728548/109395473-8f85cd80-78fa-11eb-97b5-e43f1ce0e9f7.png)

**Comment by jimkring** [comment]
We might wanna make this into a side discussion, but I’ve been thinking
that it could be really useful for Caraya to self build into a PPL at
install time.

This could be done in a post install step, sort of like a mass compile.

There are a lot of questions about how to handle RT or users who might want
to build Caraya into their executables, but it seems that 95% of users
probably would just want a faster way to run Caraya in the IDE.
-- 
Jim Sent from my mobile.

**Comment by francois-normandin** [comment]
@jimkring sure enough!

I was actually thinking about adding a Tools menu accessible shortcut to build it on demand. At the moment, it is only a build spec in the Caraya project, which I noticed was already there from a previous pull request by @ChrisStrykesAgain . All options on the table from there.

**Comment by HenrikDueholm** [comment]
You guys are really moving fast! Great news that you're including the change!

You're right regarding 'New Test (Caraya)'. In my initial build I had debugging enabled and there it was found inside the PPL everytime, which was why I moved it out. When I dropped debugging later it no longer mattered. The explicit removal you talk about probably missed it due to the changed namespace from lvlib to lvlibp. Which is the same reason the filtering failed.

For a PPL a template would be a regular VI that calls the corresponding PPL VIs. 

Another thing to note (which I didn't find important enough to mention):
The right click menu on PPL elements point to the regular VIs. In my next build I'll probably also remove right click support and just use quick-drop. To avoid using the regular Caraya from quick-drop I'll probably disconnect it so only the PPL version is available.

If you automate or include a built PPL in some way please set a pre-fix on dependencies in the build specification (to avoid crashes in executables. I used 'Caraya_').

**Comment by jimkring** [comment]
@francois-normandin I like the idea of a tools menu￼ item to build it on demand. There are also some considerations about how to palettes and users' project sources will link to the PPL instead of the lvlib.

**Comment by jimkring** [comment]
@HenrikDueholm Can you explain what you mean by "crashes in executables"? What causes the crash?￼

> If you automate or include a built PPL in some way please set a pre-fix on dependencies in the build specification (to avoid crashes in executables. I used 'Caraya_').

**Comment by HenrikDueholm** [comment]
@jimkring LabVIEW RTE doesn't handle having multiple VIs with the same qualified name but different paths in memory at the same time very well. It works fine in the development environment but it will often (if not always?) crash the RTE... that is my experience.

I always use '[PPL name]_'. As I see it that should be default when making PPLs.

**Comment by jimkring** [comment]
@HenrikDueholm I see. My thinking is that a project should be either linked to the source lvlib or the build ppl, but not both. Would the crash still happen if the PPL were called and the source lvlib was not being called by any project VIs?

**Comment by HenrikDueholm** [comment]
@jimkring: If you use a basic VI from vi.lib in two different PPLs they will have the same qualified name as they don't get the .lvlibp namespacing (because they are dependencies and not inside the library). So it's not a question of source and build but of multiple PPLs using the same user.lib/vi.lib files. You will not see the issue if you don't use multiple PPLs in the application.

I fully agree with your statement. Either you'd use the PPL edition of caraya or you'd use regular.

**Comment by jimkring** [comment]
@HenrikDueholm Ah, OK. This is an issue that I'm not very familiar with. My understanding, thus far is that:
- It only impacts RT
- it occurs if a project calls two different PPLs that each call the same VI from vi.lib (and that VI is not built into the PPLs)

Is that accurate?

**Comment by jimkring** [comment]
Also, when you add the "[PPL name]_" prefix, to which VIs are you adding the prefix? I'm a little confused by this step.

**Comment by HenrikDueholm** [comment]
Yes to the first point. it only impacts RT. So not all that relevant for Caraya, right?
No to the second point. All the dependencies (all files not in the library) are built into the PPL but they retain their qualified name. Like in an executable they'll have the .lvlibp\labvi3w (or something like that) path. This is why we get multiple files that have the same name but not the same path.

Where I add the prefix:
In the build specification in menu number four you click dependencies and add the prefix there in the bottom right corner.

**Comment by jimkring** [comment]
@HenrikDueholm Thanks. I think I'm getting closer to understanding.

Actually, a lot of people do want to run tests on RT, so this is very important to understand.

OK, I see that all the dependencies are built into the PPL, and you you say that they retain their qualified name. I'm a little confused by this and I would have thought that they would have had their name qualified such that it would not collide with the same VI in a different PPL.

Are you adding the PPL-specific name prefix only to the vi.lib/user.lib VIs that get built into the PPL?  In this way, the vi.lib/user.lib VIs get (effectively) name-spaced into the PPL. I think this was the clarification that I was missing -- exactly which VIs get the prefix.  Is that right?

**Comment by HenrikDueholm** [comment]
I figured I'd reproduce it and report it. But I could not get it to fail. Turns out that in LV2020 the dependencies are also namespaced:
Name:
![image](https://user-images.githubusercontent.com/63071979/109400233-cafab900-7947-11eb-8c30-507a12846152.png)
Path:
![image](https://user-images.githubusercontent.com/63071979/109400245-e9f94b00-7947-11eb-9a42-4117d6a1b30d.png)

I'll try it in an older version as well because now I'm feeling paranoid.

How I've been adding the prefix:
![image](https://user-images.githubusercontent.com/63071979/109400340-7b68bd00-7948-11eb-85a0-9381f5587196.png)

Don't put more thought into this before I've looked into it. I want to make sure that i'm not mistaken.

**Comment by HenrikDueholm** [comment]
Ugh it hurts to be certain but wrong!
Even in 2015 the namespace of dependency VIs is changed. So I've clearly remembered incorrectly. I'm sorry I brought up an incorrect reason for the issues I've had with PPLs through the years. 

This however does not change the fact that I've had RT issues multiple times that was fixed when I added the prefix on dependencies. And I've never had issues where I had to remove said prefix. But it really pulls the teeth from the argument when the why of it goes missing :( and when it's a sporadic issue instead of always there.

**Comment by ChrisStrykesAgain** [comment]
Wow, active thread! I haven't fully had time to digest, but think this might be relevant: https://forums.ni.com/t5/Community-Documents/Resolution-of-Pseudopaths-in-LabVIEW-Per-Target-Invocation-of/ta-p/4087124?profile.language=en

**Comment by francois-normandin** [comment]
@HenrikDueholm If you would like to test the PPL builder, it can be found in the _test package_ I added in [here:](https://github.com/JKISoftware/Caraya/issues/56#issuecomment-788505300)

This build adds a Tools menu app: 
![image](https://user-images.githubusercontent.com/11728548/109583869-96653980-7ace-11eb-827a-ccc03eed5f64.png)

Any comments are welcome...

**Comment by HenrikDueholm** [comment]
@francois-normandin I didn't see your message before now. 
I installed the new version and built the PPL through the menu app (it took some minutes, possibly due to the 2013>2020 compile?).
The product worked and my tests also still worked. I'll be using your PPL instead from now on.

Feedback for the menu app:
A text stating that the process will take some minutes and cannot be aborted.
A change of the cursor while building?
An option to enable debugging on the build could be nice. But only if your build spec for this does not result in the PPL depending on the source files.

Other than that it just works :). 

Feel free to close the issue now (or am I supposed to do that?)

**Comment by francois-normandin** [comment]
thanks for the confirmation, and great feedback. We definitely want to polish a bit more before an official release so I would like to keep this thread "open" (if you don't mind) until we resolve the final version for release. I could open new cases for tracking, but I'm sure I'll read this thread again many times between now and then anyway.

**Comment by francois-normandin** [comment]
Included in 1.2.0 to be released soon
https://github.com/JKISoftware/Caraya/milestone/6
