### ISSUE TITLE
Run Caraya unit tests from exe

### ISSUE THREAD

**Issue by AndreasStark** [JKISoftware/Caraya#132]
My use case is to deploy a Caraya test suite to a test machine that has only LV run-time installed. From there I want to run through all tests I deployed into a folder and create a JUnit result.
I tried around but every time I run my executable it does not find any test.
I first started by simply wrapping "C:\Program Files\National Instruments\LabVIEW 2020\vi.lib\addons\_JKI Toolkits\Caraya\subVIs\Run Tests Programmatically.vi" into a VI and building it into an exe, but I never get any tests to be discovered.
Any help appreciated!
Thanks in advance

**Comment by francois-normandin** [comment]
Hi @AndreasStark , 
The VI you call is using "Test Runners" under the hood, which are built on VI server... and therefore it is not available on RT targets on in the runtime engine.
In an executable, there are currently no baked-in solution to load tests from a folder and run them all.
Have a look at the "Advanced VI Tree" in the palette for an excerpt of what is available to be called from an EXE and what is not.

It would be a nice feature to add, especially if it could be made to work on an RT target (cross-platform)...

Francois

**Comment by AndreasStark** [comment]
Thanks for the fast reply! That was very helpful.
I implemented it now using the legacy suite functions.
That works now, although I also tried to build the test VIs into a lvlibp, but when I do that the suite always runs in interactive mode and creates an empty report. If you say that's not expected I'll put some code to reproduce together and open a new bug.
