### ISSUE TITLE
Rerun all tests opens about dialog when no tests were found

### ISSUE THREAD

**Issue by LogMANOriginal** [JKISoftware/Caraya#139]
Using Caraya 1.2.0.129, LV2017SP1f3

When no tests were found, `Rerun All Tests` will execute the first VI it finds in the application directory, which (currently) is `About.vi`. This could break in the future and allows execution of arbitrary code.

![image](https://user-images.githubusercontent.com/5776685/125177131-a823bf80-e1d9-11eb-8e27-75d5b03da956.png)

Steps to reproduce:
* Create an empty project
* Run Caraya from the tools menu
* Select `Rerun All Tests`

**Comment by francois-normandin** [comment]
PR #141 fixes this bug.
Will be part of next release (1.2.1).
