### ISSUE TITLE
Hook to inject an alternate "Export" format

### ISSUE THREAD

**Issue by drjdpowell** [JKISoftware/Caraya#14]
Hi, nice framework.  But I would like a means to substitute an alternate format for the exported file (I would make it JSON, but others might have other preferred formats).  It would be good to have a way to override "Basic Test Manager\Export Report.vi" or similar.

**Comment by jimkring** [comment]
Hi @drjdpowell. Yes, this would be a great feature/improvement.

Have you looked into implementation possibilities?

**Comment by francois-normandin** [comment]
The "Test Events" will need to be exposed somehow.
Currently, this is a private class of the Caraya library. Either this is exposed or better (IMO) is to wrap the info into another public class which is injected into a new Test Report class that provides the override hooks.

Test Events could be modified in the future to add more info, hence why I think it should be in a new public class to provide the best granularity for the reporter overrides.

I propose the following: 
1- Create a "Test Report" class that is injected in the "Define Test Suite" method.
2- "Test Manager:Export Report.vi" extracts "Test Events" and injects in "Test Report" class.
3- "Test Report:Export.vi" is overridable. Test Events (currently a typedef) are wrapped into a publicly accessible class.

**Comment by drjdpowell** [comment]
Sounds good.

**Comment by francois-normandin** [comment]
Implemented in release 0.6.0
Check out wiki page to get started.
https://github.com/JKISoftware/Caraya/wiki/Caraya-0.6.0-Release-Notes
