### ISSUE TITLE
Running Caraya from EXE throws error

### ISSUE THREAD

**Issue by omarmussa** [JKISoftware/Caraya#15]
I tried creating a Caraya test that would run inside of an EXE and I got this error:
<img width="251" alt="caraya_exe_error" src="https://user-images.githubusercontent.com/7425007/36569945-bd5d6166-17e4-11e8-8102-e5accf5a24a4.png">

Inspected the code and it looks like the problem is that the Get Library Info.vi has a path that is not exe compatible...

<img width="759" alt="caraya bug vi" src="https://user-images.githubusercontent.com/7425007/36570327-599ad2c4-17e6-11e8-9536-222a98bb719d.png">

I think the best way would be to migrate those files from txt files to string constants in a new VI in the Caraya lvlib as part of a package pre-build step.

**Comment by jimkring** [comment]
Hey @omarmussa -- that sounds like a good idea. I would support this change.

I'm not totally sure of the best way to do this in a pre-build step. Are you proposing to modify the Caraya sources prior to build?

A post-build script could work, unpacking the VIP, modifying the VI, saving it, repacking the VIP (but that's a lot of work)

It would be great if VIPM allowed call-backs *during* the build. But, we don't have that, yet.

**Comment by jimkring** [comment]
Hey Omar. I guess I'm fine with modifying the source files. And, it only needs to modify the source files if the defaults of the controls have actually changed (so that these files don't get modified *all the time -- on each build*)

**Comment by omarmussa** [comment]
@jimkring I thought of this idea when thinking of how the old OpenG Builder worked for stamping version numbers onto the version info cluster (or similar).  Also, you're right that it would only modify the file (from git perspective) if the text file sources changed.

**Comment by jimkring** [comment]
@omarmussa sounds good to me. Would you have interest in making this change and issuing a pull request? Also, we have implemented a [Contributor License Agreement](https://cla-assistant.io/JKISoftware/) to allow us to legitimately incorporate contributions into the project.

**Comment by omarmussa** [comment]
Yes - will post back to this issue once I have a PR ready.

**Comment by omarmussa** [comment]
Created a PR - https://github.com/JKISoftware/Caraya/pull/18

I didn't update the .vipb in the PR (with release notes/version/etc) but I built and tested locally and then built a simple EXE that called a Caraya test to ensure that it would not error when run.  Note: you have to explicitly "Aways Include" the Caraya.lvlib in the exe build spec in order to make this work.

The "Library Info Constant.vi" will get modified with each .vipb build as part of the pre-build step (because the package version number will change).  Modifications to the "Library Info" data will require manual changes to the "Library Info Constant.vi" and to the "Update Build Constants.vi" in order for those to work in built packages (manually - no enforcement currently exists).

**Comment by francois-normandin** [comment]
Implemented in release 0.6.0
