### ISSUE TITLE
Allow additional verbose explanation on the input of assert VIs

### ISSUE THREAD

**Issue by phollyni** [JKISoftware/Caraya#151]
The verbose information added by the assert VIs does not always contain all the information I want. I want to be able to add extra arbitrary information to the verbose explanation. Attached are screenshots of a vi diff showing how I would add this to the Assert Not Error vi
![Assert Not Error Diff Front Panel](https://user-images.githubusercontent.com/97617270/149180133-ab028030-c451-421e-b695-55daa7f81b9c.png)
![Assert Not Error Diff Block Diagram](https://user-images.githubusercontent.com/97617270/149180137-1c12c09b-e349-496f-b012-976d5c53ae51.png)
.

**Comment by phollyni** [comment]
I think that would also work.

**Comment by francois-normandin** [comment]
This is a new feature in [1.4.0 RC1](https://github.com/JKISoftware/Caraya/releases/tag/1.4.0_RC1)

Check out the discussion here: 
https://github.com/JKISoftware/Caraya/discussions/172
Comment welcome before this is officially released!

(Not yet released on VIPM Community.)
