### ISSUE TITLE
JUnit Test Report reports failures as skipped tests

### ISSUE THREAD

**Issue by agluck28** [JKISoftware/Caraya#156]
When generating JUnit XML reports, if there is a test failure, not an error, the XML report will state that the step was Skipped but also state the failure message is FAIL.

The issue appears to be in Caraya.lvlib:Test ReportJUnit.lvclass:Test To Report Entry.vi. When iterating through the test cases, the failures are not being passed out of the For Loop. When calculating the tests, skipped tests, errors and failures after the For Loop, errors and failures are being set to the same value and the number of actual failures are not being subtracted from the tests run causing them to be reported as skipped tests. Below image is current implementation on version 1.2.1.131

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/35640586/202793757-dea136b0-c841-445b-98b2-83d31ec7f6ac.png">

The following changes to the parsing of the results allows for failures to be correctly reported.

<img width="1070" alt="fix_junit_report" src="https://user-images.githubusercontent.com/35640586/202793843-7c0a158b-2627-4d2b-bc8c-56a1ca5f81c9.png">

**Comment by francois-normandin** [comment]
Thanks. Merge request accepted. This will be in 1.3.0 release.
