### ISSUE TITLE
Linkage bug for conditional disable

### ISSUE THREAD

**Issue by HunterJKI** [JKISoftware/Caraya#163]
Conditionally disabled structures cause false positive linking errors. EG if you have a structure that uses RT VIs when on linux that VI will always fail with linking errors. This make caraya unusable without significant manual handling of test results.

**Comment by francois-normandin** [comment]
@HunterJKI Can you provide more specifics about this?

If I understand correctly, you use RT-specific VIs in some unit tests and enclose them in a conditional disable diagram... but when you execute RunTests on a non-RT target, the linker reports an error even though the "missing VIs" would not be compiled for that target?

Seems this would need to be addressed in the Test Runner class' ReadLinkerInfo method.

There`s not much documentation on this node... perhaps some guru who develops or maintains VIPM could give us some tips? Surely this problem's been solved. How can we exclude conditionally-disabled nodes/VIs from the list? 

Perhaps there is something in the iState or viflags? Or that would be the meaning of "Exclude Edit Deps"?

![image](https://github.com/JKISoftware/Caraya/assets/11728548/c30df696-dd00-474e-9a90-ef45ee1eadd5)

**Comment by HunterJKI** [comment]
Good catch, looks like changing `Exclude Edit Deps` to true fixes it. I think we should update it to true, since I would never want edit time dependencies to cause test failures. Any objections?

**Comment by francois-normandin** [comment]
If this change does not break any tests, and we can add a currently failing test in the suite prior to implementing the change, this should go in the next release.

**Comment by francois-normandin** [comment]
FYI. 
It breaks one test: This flag also filters out the broken Tests, which has the undesirable effect of not informing the developer if a previously functional test is now broken because of a change (such as type of removal of a terminal, for example). There is certainly a mean to solve for both use cases. Investigating...

**Comment by francois-normandin** [comment]
This is fixed in [1.4.0 RC1](https://github.com/JKISoftware/Caraya/releases/tag/1.4.0_RC1)
https://github.com/JKISoftware/Caraya/discussions/172

(Not yet released on VIPM Community.)
