### ISSUE TITLE
Almost Equal inputs are inverted

### ISSUE THREAD

**Issue by SebMichaud** [JKISoftware/Caraya#164]
Hi,
Almost Equal assertion VI is the only assertion where X and Y are inverted regarding the other assertions.
X should match the expected value, not the measured one.
Best regards
Sébastien

**Comment by francois-normandin** [comment]
Inverted outputs fixed in [1.4.0 RC1](https://github.com/JKISoftware/Caraya/releases/tag/1.4.0_RC1)
https://github.com/JKISoftware/Caraya/discussions/172
