### ISSUE TITLE
Expose Event-type report class constructor in the palette of 1.4.0 release

### ISSUE THREAD

**Issue by francois-normandin** [JKISoftware/Caraya#173]
![image](https://github.com/JKISoftware/Caraya/assets/11728548/17ebc21f-ef5f-4a6c-b190-bc07aec9404c)

**Comment by jimkring** [comment]
On Sat, Jul 8, y #173 <https://github.com/JKISoftware/Caraya/issues/173>
as I on completed. I’m

> t
> Ya
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>
U--
Jim Sent from my mobile.
