### ISSUE TITLE
UTF8 encoding for reports

### ISSUE THREAD

**Issue by OlivierJourdan** [JKISoftware/Caraya#180]
If a special character is used in the report, this can cause a reading error when opened.
In my use case, Gitlab cannot list the JUnit report, making debugging harder.

I fixed the issue for my usage by adding this code 👇 
<img width="778" alt="image" src="https://github.com/JKISoftware/Caraya/assets/58081359/f3b54ca1-b7e1-4a9f-91ca-eecbaa6fd734">

I think it would be great to have this fix in the toolkit itself.

**Comment by OlivierJourdan** [comment]
Thanks for your quick feedback, @francois-normandin, and thanks for your great tool!

**Comment by francois-normandin** [comment]
Released in 1.4.3
