### ISSUE TITLE
version.txt not found

### ISSUE THREAD

**Issue by neilpate** [JKISoftware/Caraya#2]
After running a test, when the Basic Test Manager Process runs it calls *Caraya.lvlib:Get Library Info.vi*. This VI returns an error (which is then displayed by the Process state machine) as the file *version.txt* does not exist on disk.

Note I have cloned using GitHub Desktop application, not installed via VIPM, so perhaps this file is part of the packaged installation?

**Comment by tmaila** [comment]
Neil, the version.txt is generated as part of the package build process and included into the package. Git commits don't have knowledge of package versions. We should probably show N/A for version if the file is not found.

**Comment by neilpate** [comment]
Also suppress the error if the file is not found? The error dialogue popping up every time a test is run is the annoying bit.

**Comment by tmaila** [comment]
Neil, I just added the files generated by the built script to the repository

**Comment by neilpate** [comment]
Thanks Tomi, I have synch'd my local repository and now the version file not found error is no longer present.

the Help->About dialogue has a sensible version number in it now.

**Comment by tmaila** [comment]
Confirmed close by Neil Pate
