### ISSUE TITLE
Double-click on test in Caraya GUI could point to particular assert function

### ISSUE THREAD

**Issue by kosist** [JKISoftware/Caraya#20]
Right now, while double click on test in test list of Caraya GUI, VI with tests is opened. It would nice to have feature which will open that test VI, and highlight particular assert function node. 
Or, alternatively, to have right-click menu, which will allow to highlight that assert node. 
It'll help to find failing/problematic assert conditions faster and easier.

**Comment by francois-normandin** [comment]
@kosist 
This will be implemented in 0.6.0. Thanks for the suggestion.

**Comment by kosist** [comment]
That's great, happy to hear that! Thanks a lot )

**Comment by kosist** [comment]
Tested with release candidate 0.6.0.
Actually, on existing test library, I had still this behaviour, but just for tests launcher.
When new project was created, it was not observed.
But as soon as I've moved some test VIs into library, then error was present.
I attach test project (LV 2017 SP1).

Run test via Test Launcher.vi -> by double-click it is possible to navigate via test nodes, and test VIs.
When close Test Launcher.vi (and other VIs) -> error is dropped for vis, which are inside the library.
![screenshot 2018-10-24 14 56 58](https://user-images.githubusercontent.com/1911151/47432982-bdddc600-d79f-11e8-8181-b7fb1030bd07.png)
If VI stays opened, then no error is dropped.
For the VI, which is not in the library, no error is dropped, even if all VIs are closed.
[TestCaraya.zip](https://github.com/JKISoftware/Caraya/files/2510620/TestCaraya.zip)

**Comment by kosist** [comment]
Tested with release candidate 0.6.0.
It points to assert VIs, which have custom label input specified. If there is no label, then double-click does not point to the assert node. Is it expected behaviour?
I was testing it also on existing test library. And there were 8 subVIs-tests. For 6 of them, double click on main VI node, in Caraya GUI, opened VI, but dropped an error about Object Reference is invalid.
But, on new created test project this behaviour is not present, so I don't know how to reproduce it...

**Comment by francois-normandin** [comment]
Yes, the framework does not store enough info to be able to point directly to a node, so I've relied on value of the string attached to it for match. 
It's not perfect because it would not find it if in an array that calls test in a for loop.

**Comment by francois-normandin** [comment]
Ok, there is a problem with name matching when in a library. There was a fix for VI out of memory, but it does not take care to check if the VI is in a lib...
Thanks for this report, I'll track it down

**Comment by kosist** [comment]
> Yes, the framework does not store enough info to be able to point directly to a node, so I've relied on value of the string attached to it for match.
> It's not perfect because it would not find it if in an array that calls test in a for loop.

I also does not point to assert node, when multiple of them have same label (non-default label).
This case could happen within single VI, I guess (intentionally, or by mistake) - that some assert functions will have assigned same label. Then it might be confusing...

**Comment by francois-normandin** [comment]
We could go through a lot of hoops to discover which node is the likeliest to have asserted the test case being double-clicked, but I would rather modify the underlying framework code to store a reference to the node as part of the test results. It would certainly be useful information for extending the framework anyhow.
I'll create a new issue for tracking this for a future version.

**Comment by francois-normandin** [comment]
OK, experimenting a bit more with scripting to find the node, there are a few criterias that I was able to come up with to identify a few more instances. As mentioned before, Caraya does not store a reference to a particular node, just its Call Chain. So when we double-click on the test case in question, all we have for a search are the Call Chain and the name of the test.

Here's the order of search to find the Assert Node in the haystack:
1- List all Assert*.vi on the BD, if only one... highlight it. Done. If not, store the node references for future use.
2- List all string constants on the BD and filter by name of test. If found, use wires to trace back to node and highlight it.
3- Use the test name as the node name and filter for nodes that do not have any labels wired (default test name = assert VI name).
4- give up search, not enough information to discriminate.

**Comment by francois-normandin** [comment]
Implemented in release 0.6.0. 
Still some quirks when no specific text was defined for the assertion method (no other way to point to a specific method) unless it is uniquely defined otherwise (only assertion in a block diagram, for example)
