### ISSUE TITLE
Bad report generation with a hierarchy of TestCase

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#24]
[Pb Caraya Report Hierarchy.zip](https://github.com/JKISoftware/Caraya/files/2286910/Pb.Caraya.Report.Hierarchy.zip)
Using a hierarchy in Caraya (One testCase calling another TestCase, ...) creates a bad hierarchy in report file.
IHM looks good : 
![ts1bis ihm](https://user-images.githubusercontent.com/41787807/44092292-4f520720-9fd0-11e8-9a8e-a269deb28864.png)

but report generation doesn't relate the hierarchy:
![ts1bis report](https://user-images.githubusercontent.com/41787807/44092450-c056f03e-9fd0-11e8-952e-30ed30ecf7a0.png)

I created a Vi (Reorder Keys.vi) for reordering TestCases in adequation with Hierarchy before generating report string. (I had to disconnect Typedefs so it would need a slight rework).
![reorder keys in generate text report](https://user-images.githubusercontent.com/41787807/45021046-db5ca200-b030-11e8-8cd0-dddff63b6e5e.png)

generated report after reorder:
![ts1bis report after reorder](https://user-images.githubusercontent.com/41787807/44092782-cdd75d06-9fd1-11e8-8eef-69e5748995b7.png)

May this VI be integrated in a next version? Some tests for being sure it does not impact behavior may be needed.

**Comment by francois-normandin** [comment]
Fixed in release 0.6.0
