### ISSUE TITLE
Change Proposal: Make a Polymorphic VI for Assert (Request for Comments)

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#26]
**Background / Problem Statement**
There are a lot of different Assert VIs. The only way, currently, to know which ones are available is by looking on the palette.

![image](https://user-images.githubusercontent.com/381432/47173911-2d494680-d2c4-11e8-8242-b561c730b637.png)

![image](https://user-images.githubusercontent.com/381432/47174173-c11b1280-d2c4-11e8-8b72-da2840f036f5.png)

Often, one wishes to change an existing call to a different kind of Assert -- e.g. Assert Equal to Assert Not Equal, or Assert Equal Value to Assert Equal Value and Type.

![image](https://user-images.githubusercontent.com/381432/47174214-d7c16980-d2c4-11e8-8958-1c238968f58f.png)

**Proposed Solution / Poly VI**
A Polymorphic VI that shows it's selector right could make it easier for users to both (A) discover the different types of assertions and (B) replace an existing call with a different type of assertion, using the poly selector ring.  Additionally, if the poly selector ring is visible by default, it will clearly show which instance is being called, so that the user does not have to rely purely on the icon of the assertion instance to know which assertion is being called.

The following screenshot shows an example of what would be possible (however, the actual names and poly menu structure shown are just examples and not fully thought out)
![image](https://user-images.githubusercontent.com/381432/47173846-04c14c80-d2c4-11e8-96e6-b9e1af2bff17.png)

Also, we could remove all the instances of Assert from the palette and simply have a single Assert VI.

![image](https://user-images.githubusercontent.com/381432/47174356-3ab30080-d2c5-11e8-8c83-b7a655f4c43c.png)

**Comment by francois-normandin** [comment]
I really like this proposal.
- It's clean and educational for new users of the framework.
- It's easier to use with QuickDrop (we should try to make this poly VI appear at top of list when quick-dropping)
- I'd vote for the "Assert True" to be the default drop-in type

**Comment by kosist** [comment]
Cool idea, it would simplify work with the tool a lot.

**Comment by kosist** [comment]
I have changed my mind, I didn't think it though before well... 
Don't know, whether it'll be interesting for you, but let me just give some small feedback after testing with this release candidate 0.6.0.

One the one hand, it is nice to have single, poly VI which allows to select any available assert.
But on the other hand, it requires more "clicks" to get what one needs.
Just check it (without quick-dropping):
1. Go to JKI Toolkits menu.
2. Select "Caraya Test Framework".
3. Select Assert (Poly).vi, drop on block diagram.
4. Click on Polymorphic VI selector.
5. Navigate to 3 levels: Compare -> Equal -> Value.

Now we're done.

Although, with no-polymorphic VI, it could be done within 3 upper mentioned steps, without additional mouse clicks.
Moreover, when VIs are separated, it is possible to nicely configure them for quick drop; and select by it 
 most often used asserts. 
With polymorphic VI, it is possible to call just polymorphic VI -> and then anyway one needs to configure it manually.

Maybe, there could be done compromise, and there could be left both approaches on the function pallete - poly VI; and separated VIs?

**Comment by kosist** [comment]
Thanks a lot! Looks nice.
Seems, that same color will be fine - because anyway on the functions pallete Poly vi stands a bit separately (in the upper row), so it already stands out from other asserts. 
Moreover, if someone will use on the same block diagram "classic" assert VIs and polymorphic VIs - then it will be in the same visual style.

P.S. Maybe, it worth to share information about these changes on NI forum ([Unit Testing Group](https://forums.ni.com/t5/Unit-Testing-Group/gp-p/5182)), to receive more feedbacks? Because I guess not all the users of Caraya framework check github...

**Comment by francois-normandin** [comment]
FWIW, the Polymorphic VI's icon is just shown in the palette... once dropped on the block diagram, it takes the icon of whatever flavor you choose, so a different color would just highlight it.

Sharing on the different forums is a great idea. I propose that we let JKI and @jimkring review the latest code, and then we can then publicize the next build as RC2 to gather comments from the larger community before pushing it into "production".

**Comment by francois-normandin** [comment]
Implemented in the stable release of 0.6.0
