### ISSUE TITLE
Double-click on empty space of Tests indicator in the test results shows an error

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#27]
When all results are collapsed, and user double-clicks on empty space of Tests indicator, error occurs. Fixed in the way, that when tag, on which double-click was done, is empty -> do no action.

![double-click on empty space_1](https://user-images.githubusercontent.com/1911151/28896942-df045708-77de-11e7-9874-4a28af8ea961.png)
![double-click on empty space_2](https://user-images.githubusercontent.com/1911151/28896943-df04b4be-77de-11e7-8c6d-2ec18928e71c.png)

See pull request https://github.com/JKISoftware/Caraya/pull/12

**Comment by francois-normandin** [comment]
fixed in release 0.6.0
