### ISSUE TITLE
Document how to create a new report class (use of method/overrides, etc.)

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#30]
A user [asked on twitter](https://twitter.com/JonooH/status/1072557566595686400):

> will there be any more documentation on creating custom test reports? Link seem to direct to a defining a report class rather than more info on creating your own.

I [responded](https://twitter.com/jkisoftware/status/1072579237540962305).
> Hi @JonooH. Yes, we are working on more docs on creating a custom test report.  We are planning to record a video on how to create a report that outputs test results to a JSON formatted file. Stay tuned! Until then you can look at the JUnit report example.

**Comment by jimkring** [comment]
@francois-normandin we could start by documenting this in the wiki, in terms of what are the methods to implement and how they work. Or, if it's easier to just create a short video, that's great, too.

**Comment by francois-normandin** [comment]
I've uploaded a video on Youtube.
It can found found here:  https://www.youtube.com/watch?v=ZynOnumXgRE

**Comment by jimkring** [comment]
Fantastic @francois-normandin. I've added a new wiki page here that has some very crude text/documentation and points people to the new video you created:
https://github.com/JKISoftware/Caraya/wiki/Creating-Custom-Test-Reports
