### ISSUE TITLE
Assert_Equal float name change breaks existing code

### ISSUE THREAD

**Issue by neilpate** [JKISoftware/Caraya#37]
@francois-normandin and I discussed and decided to rename as "Assert Almost Equal_Float" similar to numpy: https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.testing.assert_almost_equal.html)

_Originally posted by @jimkring in https://github.com/JKISoftware/Caraya/issues/11#issuecomment-430849110_

**Comment by neilpate** [comment]
Changing the name of the assert VI breaks all my existing test VIs. I was however able to fix my code by just choosing the new name when LabVIEW complained it could not find the VI, and it seems to be ok now, but this could be confusing for a user if they did not know about this VI changing name,

**Comment by francois-normandin** [comment]
Were you using the pre-release version in production?

**Comment by neilpate** [comment]
Hmm, yes now that you mention it I might have been. I think I might have manually copied it into my Caraya directory last year some time.

**Comment by francois-normandin** [comment]
I remember it had been a while before we proposed this change and we merged it to the master branch.
Sorry for that. Hopefully it was not too much a pain to replace all.
