### ISSUE TITLE
Tests seem to run slower

### ISSUE THREAD

**Issue by neilpate** [JKISoftware/Caraya#38]
I have quite a complicated class that has approximately 550 tests. Version 0.6 could run these tests in just over a second. With 0.6.3.54 intalled the tests now take somewhere approaching 3 seconds to run. Still short but a noticeable change in speed. Speed does not seem to depend on the "Show Only Failures" value.

**Comment by francois-normandin** [comment]
0.6.1 also changed the code related to issues 31 and 32.
Do you make use of those assertions? If so, it would be expected to be lower.

for reference: 
[Fix: 31] Equal Value Comparison now asserts correctly when comparing equal typedef with non-typedef values
[Fix: 32] Added recursive verification inside cluster to assert value equality for nested values with different type representations

**Comment by neilpate** [comment]
I use almost exclusively the Assert Almost Equal_Float with DBL inputs.

**Comment by francois-normandin** [comment]
hmmm, that does not affect it. 
Can you try 0.6.1 to isolate which build caused this effect?

**Comment by jimkring** [comment]
@neilpate, just checking the obvious... did you mass compile Caraya on installation?

**Comment by jimkring** [comment]
@neilpate also, can you Profile VIs and see what bubbles to the top of the list?

**Comment by neilpate** [comment]
Just done a bit of benchmarking. Not exactly atomic clock accuracy but quite repeatable. I ignored the first few runs of my master test and then sort-of averaged out the next three or four runs.

All VIs were not mass compiled, but I did a save all when my test VIs were open which I believe would have done essentially the same thing as it seemed to save some Caraya VIs. Regardless my methodology was consistent.

Version    Approx time
0.6.3.54   2.3 s
0.6.1.51   2.3 s
0.6           1.7 s   (this may not be the official 0.6, I think I may have copied the asset float in manually).

The time difference is small but noticeable.

**Comment by neilpate** [comment]
0.6 timing profile

![image](https://user-images.githubusercontent.com/7802334/51769967-c1595400-20e4-11e9-96c6-b19118574115.png)

Interesting that vanilla "Trime Whitespace" is being used, I seem to recall some conversation years ago about getting a better performing version for OpenG or something like that.

**Comment by neilpate** [comment]
0.6.3.54 timing profile

![image](https://user-images.githubusercontent.com/7802334/51770520-5c066280-20e6-11e9-992c-e212bb05fd59.png)

Nothing jumps out at me here, actually some things look faster in time but it still feels a bit sluggish

**Comment by jimkring** [comment]
@neilpate What happens if you run your test suite programmatically with Interactive = FALSE (so that the Test Results Tree UI isn't shown)?  Do you see timing changes?

**Comment by neilpate** [comment]
If I set Interactive to FALSE (I was not previously defining a suite, I just had a master test VI), then pretty consistently my tests run in about 1.25 s _regardless of Caraya version_.

With Interactive TRUE I get similar results to as reported previously, 0.60 takes approx 1.7 s and >0.6 takes around 2.3 s

I am measuring all this by hand and my mobile phone stopwatch, so there is likely to be some error on the measurements, but I have tried to be careful.

**Comment by jimkring** [comment]
Well, I'm glad it's not an issue when running programmatically (with the UI closed), such as when doing programmatic tests on a CI Server, etc. I wonder which UI interaction implemented between 0.6 and 0.6.1.51 could have caused it.  I would have been less suprised if this UI-related performance hit showed up in 0.6.3.54, since that had some UI changes to how/when the tree populates, and I could see that if defer front panel changes were made, this would cause a performance hit.

**Comment by francois-normandin** [comment]
Closing this issue. The performance hit is from UI elements. 
We plan a refactor of the UX for version 1.0, so this benchmarking will need to be redone.
