### ISSUE TITLE
non-existing dependency

### ISSUE THREAD

**Issue by carlodri** [JKISoftware/Caraya#39]
Whenever I use Caraya in a project, there is a missing dependency (probably a leftover from packaging?) here:

![image](https://user-images.githubusercontent.com/5230366/51979489-9036a600-248d-11e9-898a-3c4e12ddcb1c.png)

**Comment by francois-normandin** [comment]
@carlodri 
I cannot reproduce this with Caraya 0.6.3 build 54. Can you confirm for which version you are seeing this?
Also, are you running from source or from the installed package?

**Comment by francois-normandin** [comment]
I've tested a build of 1.0 beta that is to be released shortly, and I cannot see this temporary rtm file in the project's dependency. I'll mark this one as closed. It looks like an artefact from a package build, but it is not present in the latest branch.

**Comment by carlodri** [comment]
@francois-normandin thanks for the feedback, and sorry for missing your requests...
