### ISSUE TITLE
Missing Assertions in Test report in particular case

### ISSUE THREAD

**Issue by OlivierLabo** [JKISoftware/Caraya#44]
I want to use Caraya for integration Test. So I have some scenari to run, calling several times a same step but in different sequences.
This leads to missing assertions results in the generated test reports.

For instance, I'm verifying a TCP connexion, creating several connexion & disconnexions.
![image](https://user-images.githubusercontent.com/41787807/53028885-0d8b8000-3468-11e9-9aeb-410ff60fa65b.png)
![image](https://user-images.githubusercontent.com/41787807/53028985-462b5980-3468-11e9-998a-c9d1f1853d05.png)
The Assertion label is defined with a default string, and is overwritten at second call to distinguish different calls to the same test case.
If we compare Results in UI and in Test reports, it misses some results
![image](https://user-images.githubusercontent.com/41787807/53029278-c8b41900-3468-11e9-906b-7c1be498be9e.png)

In the UI, there is some weird groupment of assertions, but I can understand because of VI hierarchy.
But in the test report, we can see that both second test cases (2nd Connect Default Port & 2nd Disconnect) totally disappeared.
One more thing is I don't really understand the sorting of steps in the report, and that makes harder work for verifying test execution.

**Comment by jimkring** [comment]
Hi @OlivierLabo. You're right. I think that if the same assertion label is reused for any reason, the previous result can get overwritten. This needs to be fixed.

**Comment by francois-normandin** [comment]
I confirm that the TestManager currently uses a Variant Attributes for node storage and it uses the assertion name as the identifier key. This is the same cause as the "Sort alphabetically" issue raised yesterday by Cyril. Needs to be fixed.

**Comment by francois-normandin** [comment]
This feature is implemented in the 1.0 branch.
Will be part of next release.
