### ISSUE TITLE
Use a GUID for the Key used to store each Test Result (unique per each call of Assert)

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#45]
@francois-normandin, I'm guessing you're thinking the same thing as me on this one...

Related to #44 and #40 we should generate a GUID for each Test Result, each time the Assert VI is called, and use this as the key (instead of the assertion label) for looking up results. The tree could use these GUIDs as the Node name for looking up details, after the user double-clicks, etc.

**Comment by jimkring** [comment]
@francois-normandin I've been thinking about this a little bit more, and Caraya uses VI Call Chains for tracking everything. I think that we need to extend this concept, by creating some kind of reentrant VI that generates a unique GUID for instance of an assert function (that GUID would created on first call of the reentrant VI and cached, so that the reentrant instance always outputs the same GUID) -- that's really the only want to guarantee uniqueness of an assertion.

**Comment by francois-normandin** [comment]
@jimkring 
If you're worried about GUID collisions, this is extremely unlikely. I don't know the exact order of magnitude, but it will not ever happen in our lifetime.

Why would we need the same GUID every time the same assert test is called in the hierarchy? What is the use case for keeping the same GUID for different test runs? Shouldn't we simply generate a unique ID to store in the variant attribute list? The GUID is neither sortable nor reusable in time, so it just makes sure we don't overwrite a test with the same label as used before.

If the timestamp resolution is not high enough to ensure we can sort the test assertions in the order they were called, then we would need a non-reentrant sequential number generator to allow sorting assertions that occurred at the same hierarchical level within the same microsecond.

**Comment by jimkring** [comment]
@francois-normandin OK, I think you're right. So, we dynamically create a unique GUID for each time an assertion is called. I think that will work. I took at the code and there's a LOT of shortcutting, where the link between a test and it's parent test is done using the call chain of the VIs -- to get the key of your parent, you look at your own call chain programmatically and remove yourself (the last element).  However, we'll need to somehow store this in side the variant attribute, so that each assertion also stores the key to it's parent, ahead of time.

**Comment by francois-normandin** [comment]
@jimkring I see where you're going with this. Yes, a linked list for each assertion would do. I wonder if a tree could also be a solution we should explore? (I'm thinking: recursively adding assertion results into the attribute of the caller?)

**Comment by jimkring** [comment]
@francois-normandin yes, well... it is a tree that we are trying to store :-)  Would doing the lookup of a leaf element be harder, if it's stored in a non-flat (tree) structure, since you can't just lookup of an item purely by key (e.g. like you can with a flat set of variant attributes)?

**Comment by francois-normandin** [comment]
@jimkring Indeed, if you want to look at a leaf... 
The flat list is better suited for filtering purposes (e.g. see only tests that failed) whereas test reports are easier to generate with a tree I suppose.
Flat list is probably a good bet.

**Comment by francois-normandin** [comment]
A uniqueID has been generated for each test assertion. This also had the benefit of solving #40 by creating a uniqueID that contains an incrementing iterator. The uniqueID is formed from an iterator and the clone number of the Assert Wrapper.

This issue is implemented and will be available for the planned release 1.0

**Comment by OlivierLabo** [comment]
Hi Guys,
I was about to ask how was going this point, and I'm glad to hear that it's coming soon!!
Perfectly on time for my needs !!
Great Job mates.
