### ISSUE TITLE
update Math Test Suite.vi in the examples

### ISSUE THREAD

**Issue by stagg54** [JKISoftware/Caraya#50]
Math Test Suite.vi uses the old Define Test Suite.vi  This has an input for test report type, but it is not wired on the block diagram and is of type "Default Test Report" instead of the parent "Test Report".  I assume since this function is no longer on the palettes, it is deprecated. It's kind of confusing for new users, so next time someone is messing with the examples they should update it.  This is 0.6.3.54, which is the latest showing on VIPM.  Not a big deal, but left me scratching my head for a few seconds until I figured it out.

Thanks

![Deprecated](https://user-images.githubusercontent.com/20363351/68078153-20e04080-fd96-11e9-87a7-7aec48a70674.png)

**Comment by francois-normandin** [comment]
Fixed. Will be included in next release (1.0).
