### ISSUE TITLE
Signing CLA Results in 404

### ISSUE THREAD

**Issue by stagg54** [JKISoftware/Caraya#51]
I am able to view the CLA with no problem.  When I click on the Sign in with Github to Agree button, I get a 404 page not found error.  I am signed in with Github. I tried clearing my browser cache and that did not help.  I am using opera on Windows 10.

**Comment by jimkring** [comment]
Hey Sam. Is this still an issue? I'll look into it, if you're still having trouble with the CLA -- certainly we want you to be able to contribute.

**Comment by stagg54** [comment]
Just tried it again. Still getting a 404 with both Opera and Edge on Windows 10.

**Comment by stagg54** [comment]
I opened an issue over [here](https://github.com/cla-assistant/cla-assistant/issues/573) an well.

**Comment by jimkring** [comment]
Hey Sam. Does this work?
https://cla-assistant.io/JKISoftware/Caraya

**Comment by jimkring** [comment]
@stagg54 

I'm noticing that I get a 404 if I try to open this page:

https://cla-assistant.io/JKISoftware

But, it works OK if I try to open this page:

https://cla-assistant.io/JKISoftware/

Note the trailing slash.

**Comment by stagg54** [comment]
Jim filed a  bug report with cla-assitant
[here](https://github.com/cla-assistant/cla-assistant/issues/574)
