### ISSUE TITLE
Tweak GUI iconography

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/Caraya#6]
The iconography on the GUI is a source of many questions for users.
- They are not sure what the question mark means.
- It's not very clear what the difference between grayed out verses not-grayed out means (for the icons).

![2016-08-09_11-54-18](https://cloud.githubusercontent.com/assets/381432/17529480/41297278-5e28-11e6-8a59-126ecb1da514.png)

**Comment by tmaila** [comment]
All have a meaning. We could definitely make it clearer which one is being active and make the design look better. 

- Question (gray) mark means that the test results are unknown, the test has been registered but no assert statements have been executed. 
- Cross (red) means the test failed. 
- Checkmark (blue) means the test passed. Blue was selected instead of green to aid people with red-green color blindness.

**Comment by robertbcalhoun** [comment]
How about something like this, where you get a count of the number of assertions in each state?

Also if there were some buttons that defaulted to either "close this window" if everything passes, or "take me to the first failure" if something fails, then related tickets #5 and #8 would also be partially resolved. 

![caraya close](https://cloud.githubusercontent.com/assets/5921027/18098291/76f92136-6e96-11e6-847e-31877651147b.png)

**Comment by jimkring** [comment]
These are some great usability ideas, Robert. I like how the text and count help provide more meaning to the iconography.  I also really like the "Open First Failure" button -- I might make that even more prominent.  Also, a "Rerun All Tests" button that can re-run all the tests and/or a "Re-run Individual Test" button/option might be nice.  Caraya is keeping track of the VIs associated with the tests, so it should be possible for Caraya to invoke the VI's Run method through VI Server.

**Comment by robertbcalhoun** [comment]
Jim, if you double-click on a failing test, Caraya will open that test and you can re-run it there; all that is really needed is for Caraya to auto-scroll the list to the first failure and set the focus to an "Open Test xyz" button.

I retract my suggestion for having "Export" buttons.  I just tried the programmatic execution using the Test Suite definition, and that is a better way to handle exporting test output. If I'm running interactive I don't need the output in a file.

-Rob

**Comment by jimkring** [comment]
Hi Rob. Again, great points: I agree that the real need is to find/open the first failure and re-run it.  I think we should try adding that and see how the workflow feels after some use.

**Comment by jimkring** [comment]
This was implemented a while ago. Here's the latest.

![image](https://user-images.githubusercontent.com/381432/51629908-a082da00-1efd-11e9-9c89-2a57f004ac65.png)
