### ISSUE TITLE
Error 1059 in Batch Testing tool if non-VI file present

### ISSUE THREAD

**Issue by pollockm** [JKISoftware/Caraya#60]
Looks like the code might not be checking for valid file extension before trying to load:
![image](https://user-images.githubusercontent.com/5288961/71690165-85555700-2d69-11ea-97b4-c6648142404d.png)

**Comment by pollockm** [comment]
Reproducible if there is any file in the specified directory that is not a .vi file (such as readme.txt)

**Comment by francois-normandin** [comment]
Confirmed. We'll put a filter on the recursive file listing to only include *.vi.
Are there any other files that should be included? (*.vim maybe???)

**Comment by pollockm** [comment]
vi, vim, vit are the only ones that I can think of.  How would this handle llb or lvlibp cases?

**Comment by francois-normandin** [comment]
Fixed and unit test created to verify.
Will be in the next beta package
