### ISSUE TITLE
Error 1 in Batch Testing tool if Output Folder left blank

### ISSUE THREAD

**Issue by pollockm** [JKISoftware/Caraya#61]
![image](https://user-images.githubusercontent.com/5288961/71690393-30fea700-2d6a-11ea-897a-50eb305e1b21.png)

![image](https://user-images.githubusercontent.com/5288961/71690405-39ef7880-2d6a-11ea-81d8-c13108e4ae33.png)

Prefer to disable the Run All Tests button until output folder is populated or provide clearer error.

**Comment by francois-normandin** [comment]
I thought I had that one covered. We'll need both a better error description and to disable the button.
The button is bypassed when running in Silent mode, which is needed for the CLI. That means we should detect and throw the appropriate error. I'll add a new issue to select a range for Caraya errors and document them i the wiki. As of now, they are mostly error 1 or error 42, both generic.

**Comment by francois-normandin** [comment]
When in Manual mode, the Run Tests button will be disabled.
When in Silent mode, it will now return a Test Report error (depending on context) as listed below:

- Error 7230: Generic Test Report error
- Error 7231: Invalid report path
- Error 7232: Report path is empty or relative. Use an absolute path.
- Error 7233: Unexpected file type.
- Error 7234: Directory not found.
