### ISSUE TITLE
JUnit report "skipped" and "failures" don't match results (v0.6.3.54)

### ISSUE THREAD

**Issue by arjen-hiemstra** [JKISoftware/Caraya#68]
The counters for skipped and failures in the jUnit report don't match the actual test results.
For now it seems to me failures are listed as "skipped" and "failures" is always 0.

**Comment by francois-normandin** [comment]
@arjen-hiemstra 
You are correct. This has been noticed and fixed in the upcoming 1.0 release.
I'll include a line about this issue being fixed in the final 1.0 release notes.

**Comment by francois-normandin** [comment]
Available in pre-release build 72
https://github.com/JKISoftware/Caraya/releases/tag/1.0.0.72
