### ISSUE TITLE
Error 7002 with test suites - error description needed

### ISSUE THREAD

**Issue by pollockm** [JKISoftware/Caraya#69]
Using release 1.0.0.72 with LabVIEW 2019, I see error 7002 get returned from Destroy Test Suite if there is any failing test in the test suite.

Is this intentional?  Looks like it gets sent via the Test Assert Factory notifier on any failing test from the test manager VI.

If it is intentional, it would be great to have something other than this get reported:
![image](https://user-images.githubusercontent.com/5288961/73110965-0f5a9080-3ece-11ea-89be-80ddf4757b85.png)

Perhaps when sending the 7002 error, we could include a more descriptive error message?

**Comment by pollockm** [comment]
![image](https://user-images.githubusercontent.com/5288961/73111015-4466e300-3ece-11ea-8a55-5c7129a6cf8e.png)

**Comment by pollockm** [comment]
Reading the recently posted https://github.com/JKISoftware/Caraya/wiki/Caraya-Error-Codes page, looks like error 7002 is indeed expected.  I'd hope that the error message would return the same kind of content as what is written on that page ("Test Suite failed").

**Comment by francois-normandin** [comment]
There must be two places where the same error code is generated and this one does not have the error description. I used the text of that description to fill in the wiki.
Thanks @pollockm it will be corrected for the official release.

**Comment by francois-normandin** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/11728548/73112581-fb6a5b00-3edc-11ea-86b4-61b8d375cb6f.png)

Does anyone know how to effectively get rid of the "Undefined error" paragraphs? I assume there is a way to install user-defined error codes somewhere in the LabVIEW directory...

**Comment by francois-normandin** [comment]
Found this resource: https://forums.ni.com/t5/LabVIEW-Idea-Exchange/Error-txt-file/idc-p/1042153/highlight/true#M3568

I'll see if I can add the Caraya error list to the LV folder. Would make for a better error code experience.

**Comment by francois-normandin** [comment]
Ohhh, that's so sweet... I learned something today!

![image](https://user-images.githubusercontent.com/11728548/73113024-7d5b8380-3edf-11ea-9157-4e7cffad58f6.png)

**Comment by pollockm** [comment]
Thanks!

**Comment by francois-normandin** [comment]
You are the one to thank!
