### ISSUE TITLE
Caraya library missing Application Menu.rtm

### ISSUE THREAD

**Issue by pollockm** [JKISoftware/Caraya#70]
I'm writing some tests to verify that there are no missing items in a project, and Caraya itself is failing the test.  Looks like an incorrect linkage to Application Menu.rtm, which it flags as expecting at C:\Application Menu.rtm

![image](https://user-images.githubusercontent.com/5288961/73116153-38434b80-3ef7-11ea-894a-c491c35bad6e.png)

![image](https://user-images.githubusercontent.com/5288961/73116173-80626e00-3ef7-11ea-9126-86e857922598.png)

This is in 1.0.0.72

**Comment by francois-normandin** [comment]
@pollockm 
Good catch. Do you use VI Analyzer for these tests? If so, can you share them?

**Comment by pollockm** [comment]
I'm building a small suite of tests that run on the project level via Caraya for continuous integration purposes.  They'll be open sourced once I find a good place for them to live.  Tests include:

Broken VIs
Missing items
Cross-linked items (anything not in the same hierarchy as the project file or installed directories like vi.lib)
Caraya tests that don't live in the \tests subdirectory of the project folder
Items incorrectly claimed by a library
Project conflicts

These cover the lowest hanging fruit in terms of issues I want my CI system to catch, so making a reuse component that has those and the necessary scripts to run them in a pipeline

**Comment by francois-normandin** [comment]
Awesome.
I'm referencing a new feature request here: #71

**Comment by francois-normandin** [comment]
It might be a VIPM bug. The menu is linked properly in the source folder, but not in the installed folder. I'll find out if it is a VI Package Build Spec problem or a bug altogether and report it accordingly.

I am considering also to exclude the lvproj file from the installation as some of the methods cannot relink properly after installation (such as those methods deployed in Tools and Examples folders). There are many VIs that cannot be found where the project file expects them to be.

**Comment by francois-normandin** [comment]
I've fixed it by removing the rtm file from Caraya.lvlib. This is a workaround to VIPM bug reported [here.](https://forums.jki.net/topic/3068-app-menu-rtm-file-does-not-relink-properly-on-package-build/)
