### ISSUE TITLE
Batch Runner - Junit instead of XML for report type

### ISSUE THREAD

**Issue by pollockm** [JKISoftware/Caraya#75]
This is a stupidly minor issue, but one that caused me to check the source code to be sure.

When running unit tests in a CI environment, I'm usually looking for JUnit format for my reports.  

The batch runner has XML or Plain Text as the options.  I was looking for a JUnit option since that is how the test suite function polymorphic VI lists the option, and wasn't sure if the XML format was the same as JUnit.  

It is the same JUnit implementation, so I was hoping that the enum would list Plain Text and JUnit instead of Plain Text and XML.

**Comment by francois-normandin** [comment]
@pollockm  How about this? 
![image](https://user-images.githubusercontent.com/11728548/73221264-69599100-412e-11ea-96e6-4fa18a43d075.png)

(It does not break anything to change. It is a new feature and this control is not exposed on the conpane of the batch runner VI anyway...)

**Comment by pollockm** [comment]
Sure, works for me.  

<pedantry>I believe the correct usage is JUnit, not J-Unit </pedantry>

**Comment by francois-normandin** [comment]
👍 I'll change it.

**Comment by francois-normandin** [comment]
done
