### ISSUE TITLE
Error 1 occurred at Send Notification - Random Error dialog

### ISSUE THREAD

**Issue by laxmanraok** [JKISoftware/Caraya#82]
I started getting this error after evaluating beta for some of the tests I was doing.
![image](https://user-images.githubusercontent.com/49143725/79715966-d4ac9c80-82f2-11ea-9e6c-a45bcb9a67e2.png)

With some preliminary investigations/comparison I observed that JUnit file was not created until this error is poped out. I also see that when this error happens, the error 7003 occurs. I compared it with the older release and found that the timeout is different i.e. 1.0 sec (1000ms) where as the older release waits indefinitely (-1) at the Destroy Test Suite. I am able to fix this by using a longer time out (I used 10sec) and found that the time taken to execute the Destroy Test Suite is greater than 1 sec (1000ms) which is the default value of the framework. May be it is good to have this default timeout value higher?

I am using LV2016SP1.

**Comment by laxmanraok** [comment]
It will be good if we can configure the timeout for this VI as well.
...\addons\_JKI Toolkits\Caraya\subVIs\Run Tests Programmatically.vi

**Comment by francois-normandin** [comment]
@laxmanraok thanks for the report.
I have stumbled on this and the timeout has been changed to 2000ms in an unreleased build 89 that I'm using for final verification.
Based on your feedback, I might increase it further and will look into adding a timeout on the programmatic run method.
Good catch and good suggestion!

**Comment by francois-normandin** [comment]
@laxmanraok Default timeout has been increased to 2000 ms, and a terminal has been added to the Run Test method. This will be part of version 1.0.0 after final review is completed.

**Comment by laxmanraok** [comment]
@francois-normandin - I tried the released version today and I am still getting this error. I haven't played much with it but I was able to create a constant in ...\addons_JKI Toolkits\Caraya\subVIs\Run Tests Programmatically.vi and change it to 5000 to make it work. I am not sure if I am running on a slow PC!

**Comment by laxmanraok** [comment]
Actually the problem is that the file is created late and my build expects to find a file and so throws an error.
