### ISSUE TITLE
Verify that upstream error skips the tests

### ISSUE THREAD

**Issue by francois-normandin** [JKISoftware/Caraya#92]
A bug happened during the VIWeek presentation which took me completely by surprise. I was expecting a downstream test to be skipped because of an upstream error, and it just ran.
Not sure what happened, but this is to be investigated ASAP because the 110+ unit tests dod not catch that one.

**Comment by francois-normandin** [comment]
OK, I got more info on this bug and why it was not captured in the 123 tests.
It turns out that the bug only occurs when the "Assert Only" flag is false... but because the tests need to pass, we use the "Assert Only" = True flag to test for failures. Otherwise, registering for a unit test that fails (and is registered) will make the test fail... Chicken and the egg problem.

I'll fix the bug alright, but we'll need to come up with a decent way to test for all the tests that should fail. It might be possible to ensure this is happening by creating a Test Runner and harness the pre-build actions for all the tests that are supposed to fail. Interesting that we found this bug live during a presentation! I love it.

**Comment by jimkring** [comment]
I guess that’s one great reason to demonstrate and have code reviewed.
Also, having meeting host randomly ask you to do things (you don’t normally
expect to do) is a great way of exercising different paths of execution :-)
-- 
Jim Sent from my mobile.

**Comment by francois-normandin** [comment]
OK, fixed it.
That is actually a Hotfix that we'll want to release asap.

![image](https://user-images.githubusercontent.com/11728548/82736654-6bf17f00-9cf9-11ea-86c9-c24bb94b49f0.png)

**Comment by francois-normandin** [comment]
Released in 1.0.2.115
