### ISSUE TITLE
Create a Pre-Build test in VI Package build workflow

### ISSUE THREAD

**Issue by francois-normandin** [JKISoftware/Caraya#94]
To capture hard-to-catch failures such as #92 (where we actually want to make sure we have a failure), we should have a pre-build VI package test that prevents building the package from being built if those tests do not fail.

**Comment by francois-normandin** [comment]
feature implemented - will be available in next release

**Comment by jimkring** [comment]
@francois-normandin I created a new "dev-task" label for items that aren't user-facing enhancements.
