### ISSUE TITLE
Error Re-Running Tests

### ISSUE THREAD

**Issue by JamesMc86** [JKISoftware/Caraya#98]
I'm not sure what the important conditions are but I have started a project with Caraya.

All my tests are contained within a lvlib and when I use Tools>Caraya>Run Tests in Active Project then everything works as I expected.

When I then select Action>Re-run All Tests then I get error 1004
![image](https://user-images.githubusercontent.com/4404192/85857863-887a4e80-b7b2-11ea-897d-ba9fd084fb14.png)

Only edit has been in the class under test - not the test VIs themselves.

**Comment by francois-normandin** [comment]
@JamesMc86  When Caraya runs from the tools menu, it is supposed to run your tests in the project's app space, but I'll hazard a guess that the UI is in a different application reference. Rerun tests would fail of the VIs have left memory in the appRef.

It's a bug with this rerun feature, nothing wrong with your code or how you're supposed to use the framework.

**Comment by francois-normandin** [comment]
Fixed in next release
