### ISSUE TITLE
Link in Readme to NIWeek Video does not work

### ISSUE THREAD

**Issue by cycleworm** [JKISoftware/Caraya#99]
Hi, the link in the document refering to the niweek video does not work. Could you please update the link. Thanks.
![image](https://user-images.githubusercontent.com/493769/88162186-473e5880-cc11-11ea-9260-f2e275001ced.png)

http://content.jki.net/caraya-new-take-on-labview-unit-testing-niweek-2016-presentation

**Comment by francois-normandin** [comment]
@jvr-ruiz @ericwelden This one is for you guys.

**Comment by jimkring** [comment]
Thanks for letting us know @cycleworm.

I've updated the video link to this one:
https://youtu.be/zwTFsyoUIKY

The video is still being processed on youtube, since I just uploaded it, so it might take some minutes for that to finish up before you can watch it.
